services:
  postgres_test:
    image: postgis/postgis:15-3.4
    container_name: hoarding_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoarding_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:alpine
    container_name: hoarding_redis_test
    ports:
      - '6380:6379'
    volumes:
      - redis_test_data:/data

volumes:
  postgres_test_data:
  redis_test_data:
